### ISSUE TITLE
IO.java does not compile with addition of ".get()" on line 19

### ISSUE THREAD

**Issue by rondagostino** [Datomic/datomic-java-examples#3]
The transactAll() method in IO.java needs to either wrap exceptions thrown by the get() call with RuntimeException or declare thrown exceptions in its signature, and if it does the latter then callers also have to change to declare thrown exceptions or add a try/catch block.

**Comment by benkamphaus** [comment]
Hi @rondagostino, we didn't update when this occurred but this issue was resolved by: https://github.com/Datomic/datomic-java-examples/commit/3f4d6042177fcdfd5f75b5769eb2ac2799c58fd3
